services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      APP_ENV: 'dev'

    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    command: bash
